# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8.11.1

stages:
  - DEVELOP
  - RELEASE
  - MASTER
before_script:
# firebase login:ci
  - npm install -g firebase-tools
  - npm install
  - unset CI # clear the node evironment 'CI' in Docker  

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:

WWW-CHATSHIER:
  stage: DEVELOP
  script:
    - cp src/config/url-config-dev.js src/config/url-config.js
    - npm run build
    - firebase use dev-chatshier --token ${FIREBASE_DEV_TOKEN}
    - firebase deploy --only hosting --token ${FIREBASE_DEV_TOKEN}
  only:
    refs:
      - develop

WWW-DSDSDS:
  stage: DEVELOP
  script:
    - cp src/config/url-config-dev.js src/config/url-config.js
    - npm run build
    - firebase use dev-dsdsds --token ${FIREBASE_DEV_TOKEN}
    - firebase deploy --only hosting --token ${FIREBASE_DEV_TOKEN}
  only:
    refs:
      - develop


WWW-CHATSHIER:
  stage: RELEASE
  script:
    - cp src/config/url-config-dev.js src/config/url-config.js
    - npm run build
    - firebase use rel-chatshier --token ${FIREBASE_REL_TOKEN}
    - firebase deploy --only hosting --token ${FIREBASE_REL_TOKEN}
  only:
    refs:
      - release

WWW-DSDSDS:
  stage: RELEASE
  script:
    - cp src/config/url-config-dev.js src/config/url-config.js
    - npm run build
    - firebase use rel-dsdsds --token ${FIREBASE_REL_TOKEN}
    - firebase deploy --only hosting --token ${FIREBASE_REL_TOKEN}
  only:
    refs:
      - release