# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.10.0

pipelines:  
  branches:
    default:
      - step:
          script:
            - rm -Rf ~/.ssh/known_host
    develop:
      - step:
          script:
            - sudo chown -R $USER ~/.config/configstore
            - npm install -g firebase-tools
            - npm install
            - npm run build
            - firebase use dev-chatshier --token ${FIREBASE_DEV_TOKEN}
            - firebase deploy --only hosting --token ${FIREBASE_DEV_TOKEN}
            - echo "[SUCCEEDED] develop has been deployed."
    release:
      - step:
          script:
            - echo "[SUCCEEDED] release has been deployed."
    master:
      - step:
          script:
            - echo "[SUCCEEDED] master has been deployed."

